---
- name: Install Redis packages
  become: yes
  become_user: root
  command: "{{ item }}"
  with_items:
    - apt-get update
    - apt install libc6-dev -y
    - wget http://download.redis.io/releases/redis-5.0.7.tar.gz
    - tar xzf redis-5.0.7.tar.gz
    
- name: Run command
  command: make MALLOC=libc
  args:
    chdir: /root/hoanm/redis-5.0.7
  when:
    - inventory_hostname == groups['redis_cluster'][0]
    
- name: Run command
  command: make MALLOC=libc
  args:
    chdir: /root/redis-5.0.7
  when:
    - inventory_hostname != groups['redis_cluster'][0]

- name: Create Systemd
  template: src=redis.service.first.j2 dest=/etc/systemd/system/redis.service
    owner=redis group=redis mode=0644
  when: 
    - inventory_hostname == groups['redis_cluster'][0]

- name: Create Systemd
  template: src=redis.service.j2 dest=/etc/systemd/system/redis.service
    owner=redis group=redis mode=0644
  when:
    - inventory_hostname != groups['redis_cluster'][0]
